name = "DeepDish"
uuid = "c8268ee2-ff8a-11e8-08d6-7b22c901c8a1"
authors = ["vilim <vilim.stih@gmail.com>"]
license = "MIT"
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]